# -*- coding: utf-8 -*-
"""
/***************************************************************************
 JupyterQGIS
                                 A QGIS plugin
 Plugin that starts a Jupyter Notebook with the PyQGIS environment.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-11-10
        copyright            : (C) 2021 by Fran Martín
        email                : fmartinrivas2@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load JupyterQGIS class from file JupyterQGIS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .jupyter_qgis import JupyterQGIS
    return JupyterQGIS(iface)
